import { Headroom } from "@/components/headroom";
import { Footer } from "@/components/layout/footer";
import { Navbar } from "@/components/layout/navbar";
import { NavbarSpacer } from "@/components/layout/navbar/navbar-spacer";
import { ModeToggle } from "@/components/mode-toggle";
import { ThemeProvider } from "@/components/theme-provider";
import { FOOTER_HEIGHT } from "@/constants/layout";
import type { Metadata } from "next";
import { Geist_Mono, Lato } from "next/font/google";
import "./globals.css";

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"], // choose only what you need
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${lato.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Headroom>
            <Navbar />
          </Headroom>
          <main
            style={{
              minHeight: `calc(100vh - ${FOOTER_HEIGHT}px)`,
            }}
          >
            <NavbarSpacer />
            {children}
          </main>
          <Footer />
          <div className="fixed bottom-18 left-5">
            <ModeToggle />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
