export interface WeddingGalleryImage {
  url: string;
  title: string;
  description: string;
  aspect: "portrait" | "landscape";
  width: number;
  height: number;
}

export const weddingGallery: WeddingGalleryImage[] = [
  {
    url: "http://emanueldellapia.com/E_weddings/Bride -30 years old -portrait -cover-warm color-sunset-sun on hair italian bride-sexy-outdoors-1 small.jpg",
    title: "Golden Hour Portrait",
    description:
      "Stunning bridal portrait bathed in warm sunset light, capturing the elegant beauty of an Italian bride outdoors",
    aspect: "portrait",
    width: 2000,
    height: 3008,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/Bride -30 years old -portrait -cover-warm color-sunset-sun on hair italian bride-sexy-outdoors-at mirror-sexy-1 small.jpg",
    title: "Mirror Reflection at Sunset",
    description:
      "Intimate bridal moment captured through a mirror with golden sunset tones illuminating her hair",
    aspect: "portrait",
    width: 2000,
    height: 3008,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/Bride at the mirror retouch make up small.jpg",
    title: "Final Touch",
    description:
      "Bride perfecting her makeup at the mirror in preparation for the ceremony",
    aspect: "landscape",
    width: 2000,
    height: 3008,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/Bride trough the flowers to the guests 1 small.jpg",
    title: "Through the Garden",
    description:
      "Bride walking through blooming flowers toward awaiting guests",
    aspect: "landscape",
    width: 2000,
    height: 3008,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/Bride-30 years old-caucasian-happy-smiling-alone -in white dress-in the garden of castle-8 small.jpg",
    title: "Castle Garden Portrait",
    description:
      "Radiant bride smiling in white dress among the romantic gardens of a historic castle",
    aspect: "portrait",
    width: 2000,
    height: 3008,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/DSC_0412 small.jpg",
    title: "Ceremony Preparations",
    description:
      "Candid moment capturing the anticipation before the wedding ceremony begins",
    aspect: "landscape",
    width: 1488,
    height: 2240,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/DSC_0416 small.jpg",
    title: "Elegant Details",
    description:
      "Close-up of wedding day details highlighting the careful attention to every element",
    aspect: "portrait",
    width: 1488,
    height: 2240,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/DSC_0420 small.jpg",
    title: "Bridal Veil",
    description:
      "Delicate veil captured in soft natural light during preparations",
    aspect: "portrait",
    width: 1488,
    height: 2240,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/DSC_0423  small.jpg",
    title: "Reception Atmosphere",
    description: "Warm ambient shot of the wedding reception venue and guests",
    aspect: "landscape",
    width: 1488,
    height: 2240,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/DSC_0426 small.jpg",
    title: "Emotional Exchange",
    description:
      "Intimate moment shared between loved ones during the celebration",
    aspect: "landscape",
    width: 1488,
    height: 2240,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/DSC_0430 small.jpg",
    title: "Wedding Party",
    description:
      "Joyful gathering of wedding party members celebrating together",
    aspect: "landscape",
    width: 1488,
    height: 2240,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/DSC_0447 small.jpg",
    title: "Ceremony Blessing",
    description: "Sacred moment during the wedding ceremony officiation",
    aspect: "landscape",
    width: 1488,
    height: 2240,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/DSC_0452 small.jpg",
    title: "Ring Exchange",
    description:
      "The meaningful exchange of wedding rings between bride and groom",
    aspect: "portrait",
    width: 1488,
    height: 2240,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/DSC_0457 small.jpg",
    title: "Newlywed Joy",
    description: "Pure happiness radiating from the newly married couple",
    aspect: "landscape",
    width: 1488,
    height: 2240,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/DSC_0586 small.jpg",
    title: "First Dance",
    description:
      "Romantic first dance as husband and wife surrounded by loved ones",
    aspect: "landscape",
    width: 2240,
    height: 1488,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/DSC_3503  s.jpg",
    title: "Outdoor Celebration",
    description:
      "Open-air wedding celebration with guests mingling in natural surroundings",
    aspect: "landscape",
    width: 2848,
    height: 4288,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/DSC_3515 s.jpg",
    title: "Table Settings",
    description: "Beautifully arranged reception tables with elegant décor",
    aspect: "landscape",
    width: 2848,
    height: 4288,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/DSC_3516 s.jpg",
    title: "Floral Centerpiece",
    description: "Stunning floral arrangement adorning the reception table",
    aspect: "portrait",
    width: 2848,
    height: 4288,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/DSC_3527 s.jpg",
    title: "Toast to Love",
    description: "Champagne glasses raised in celebration of the newlyweds",
    aspect: "portrait",
    width: 2848,
    height: 4288,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/DSC_3541 s.jpg",
    title: "Guest Candids",
    description: "Natural moments of guests enjoying the wedding festivities",
    aspect: "landscape",
    width: 2848,
    height: 4288,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/DSC_3550 s.jpg",
    title: "Couple Portrait",
    description: "Timeless portrait of bride and groom in their wedding attire",
    aspect: "portrait",
    width: 2848,
    height: 4288,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/DSC_3555 s.jpg",
    title: "Loving Embrace",
    description: "Tender embrace between the newlyweds captured in soft light",
    aspect: "portrait",
    width: 2848,
    height: 4288,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/DSC_3567 s.jpg",
    title: "Venue Architecture",
    description:
      "Architectural beauty of the wedding venue framing the celebration",
    aspect: "landscape",
    width: 2848,
    height: 4288,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/DSC_3573 s.jpg",
    title: "Wedding Cake",
    description:
      "Magnificent multi-tiered wedding cake awaiting the cutting ceremony",
    aspect: "portrait",
    width: 2848,
    height: 4288,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/DSC_3579 s.jpg",
    title: "Dance Floor Energy",
    description: "Guests dancing and celebrating with unbridled joy",
    aspect: "landscape",
    width: 2848,
    height: 4288,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/DSC_3590 s.jpg",
    title: "Evening Atmosphere",
    description:
      "Romantic evening ambiance as the celebration continues into the night",
    aspect: "landscape",
    width: 2848,
    height: 4288,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/DSC_3591 s.jpg",
    title: "Candlelight Glow",
    description:
      "Warm candlelight creating an intimate atmosphere at the reception",
    aspect: "landscape",
    width: 2848,
    height: 4288,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/DSC_3618 s.jpg",
    title: "Family Gathering",
    description: "Multi-generational family members united in celebration",
    aspect: "landscape",
    width: 2848,
    height: 4288,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/DSC_3620 s.jpg",
    title: "Heartfelt Speeches",
    description:
      "Emotional speeches from family and friends honoring the couple",
    aspect: "landscape",
    width: 2848,
    height: 4288,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/DSC_3636 s.jpg",
    title: "Bouquet Toss",
    description: "The traditional bouquet toss moment with eager guests",
    aspect: "landscape",
    width: 2848,
    height: 4288,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/DSC_3649 s.jpg",
    title: "Grand Exit",
    description: "Couple making their grand exit as newlyweds amid celebration",
    aspect: "landscape",
    width: 2848,
    height: 4288,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/DSC_3650 s.jpg",
    title: "Farewell Send-Off",
    description: "Guests waving farewell to the departing newlyweds",
    aspect: "landscape",
    width: 2848,
    height: 4288,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/Escape of the Bride  black and white photo 1 small.jpg",
    title: "Escape of the Bride",
    description:
      "Artistic black and white capture of the bride in a spontaneous moment",
    aspect: "portrait",
    width: 2000,
    height: 3008,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/SVATBA 2007 ANNA 024 small.jpg",
    title: "Anna's Wedding - Ceremony",
    description:
      "Beautiful ceremony moment from Anna's 2007 wedding celebration",
    aspect: "landscape",
    width: 900,
    height: 1200,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/SVATBA 2007 ANNA 029 small.jpg",
    title: "Anna's Wedding - Bridal Portrait",
    description: "Elegant bridal portrait of Anna radiating happiness",
    aspect: "portrait",
    width: 900,
    height: 1200,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/SVATBA 2007 ANNA 085 small.jpg",
    title: "Anna's Wedding - Reception Joy",
    description: "Joyful reception moments at Anna's wedding celebration",
    aspect: "landscape",
    width: 1200,
    height: 900,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/Smiling Bride  in the city  Black and White  contrast small.jpg",
    title: "Urban Elegance",
    description:
      "High-contrast black and white portrait of smiling bride in city setting",
    aspect: "portrait",
    width: 2000,
    height: 3008,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/Smiling Bride in white 1 small.jpg",
    title: "Pure Joy",
    description: "Radiant bride in white dress with genuine smile of happiness",
    aspect: "portrait",
    width: 2000,
    height: 3008,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/Smiling Bride outdoor 1 small.jpg",
    title: "Outdoor Radiance",
    description: "Bride smiling warmly in natural outdoor setting",
    aspect: "portrait",
    width: 2000,
    height: 3008,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/Smiling bride in white at sunset 1 small.jpg",
    title: "Sunset Smile",
    description: "Bride in white dress illuminated by golden sunset light",
    aspect: "portrait",
    width: 2000,
    height: 3008,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/Svatba Giovanni a Anna - 26-8-2011 017.jpg",
    title: "Giovanni & Anna - Getting Ready",
    description:
      "Pre-ceremony preparations from Giovanni and Anna's August 2011 wedding",
    aspect: "landscape",
    width: 400,
    height: 602,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/Svatba Giovanni a Anna - 26-8-2011 022.jpg",
    title: "Giovanni & Anna - Bridal Details",
    description: "Beautiful details from the bride's preparations",
    aspect: "portrait",
    width: 400,
    height: 602,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/Svatba Giovanni a Anna - 26-8-2011 129.jpg",
    title: "Giovanni & Anna - Ceremony Moments",
    description: "Touching ceremony moment between Giovanni and Anna",
    aspect: "landscape",
    width: 400,
    height: 602,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/Svatba Giovanni a Anna - 26-8-2011 183.jpg",
    title: "Giovanni & Anna - Wedding Portrait",
    description: "Classic wedding portrait of the newly married couple",
    aspect: "portrait",
    width: 400,
    height: 602,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/Svatba Giovanni a Anna - 26-8-2011 216.jpg",
    title: "Giovanni & Anna - Reception Celebration",
    description: "Lively reception moments with guests celebrating together",
    aspect: "landscape",
    width: 400,
    height: 602,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/Svatba Giovanni a Anna - 26-8-2011 224.jpg",
    title: "Giovanni & Anna - Romantic Dance",
    description: "Intimate dance moment between Giovanni and Anna",
    aspect: "landscape",
    width: 400,
    height: 602,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/Svatba Giovanni a Anna - 26-8-2011 229.jpg",
    title: "Giovanni & Anna - Family Bonds",
    description: "Meaningful family moments at the wedding celebration",
    aspect: "landscape",
    width: 400,
    height: 602,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/Svatba Giovanni a Anna - 26-8-2011 312.jpg",
    title: "Giovanni & Anna - Evening Festivities",
    description: "Evening celebration with guests enjoying the festivities",
    aspect: "landscape",
    width: 400,
    height: 602,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/Svatba Giovanni a Anna - 26-8-2011 317.jpg",
    title: "Giovanni & Anna - Candid Joy",
    description: "Spontaneous joyful moment captured during the celebration",
    aspect: "landscape",
    width: 400,
    height: 602,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/Svatba Giovanni a Anna - 26-8-2011 319.jpg",
    title: "Giovanni & Anna - Guest Celebration",
    description: "Guests celebrating with energy and happiness",
    aspect: "landscape",
    width: 400,
    height: 602,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/Svatba Giovanni a Anna - 26-8-2011 366.jpg",
    title: "Giovanni & Anna - Night Portraits",
    description: "Stunning evening portraits of the couple",
    aspect: "portrait",
    width: 400,
    height: 602,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/Svatba Giovanni a Anna - 26-8-2011 368 filter 1.jpg",
    title: "Giovanni & Anna - Artistic Close",
    description:
      "Artistic filtered image capturing the essence of their special day",
    aspect: "landscape",
    width: 400,
    height: 602,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/The smiling Bride 3 color small.jpg",
    title: "Vibrant Bride",
    description: "Colorful portrait showcasing the bride's radiant smile",
    aspect: "portrait",
    width: 2000,
    height: 3008,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/bride and spouse -30-40 years old -wedding day outdoor-happyness-smiling -with flower 2 small.jpg",
    title: "Couple with Flowers",
    description:
      "Happy couple smiling together with wedding flowers in outdoor setting",
    aspect: "landscape",
    width: 2000,
    height: 3008,
  },
  {
    url: "http://emanueldellapia.com/E_weddings/smiling Running Bride in white clothes  3 small.jpg",
    title: "Bride in Motion",
    description:
      "Joyful bride running in white dress, capturing spontaneous happiness",
    aspect: "portrait",
    width: 2000,
    height: 3008,
  },
];
